# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
report_sizes: true
nfpms:
  - id: made
    package_name: made
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - made
    vendor: Madecommand
    homepage: https://github.com/madecommand/made
    maintainer: Guillermo Álvarez <guillermo@cientifico.net>

    description: |-
      made is a command line tool that automates the execution of commands defined in Madefiles and Makefiles, searching for these files in various directories, concatenating their sections, and producing a shell script for execution. It extends the functionality of make by reading not only the Makefile/Madefile in the current directory but also Madefiles in different locations within the system. 

    license: GPL-3.0
    formats:
      - deb
      - rpm
      - archlinux 
    dependencies:
      - zsh
    provides:
      - made
    recommends:
      - bash
    bindir: /usr/bin

    priority: extra


